//Alexander Tu
// 02/11/2025

// Dylan Hartley
// 12/12/2025

import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/Navbar";
import SessionProvider from "~/components/SessionProvider";
import ChatWidget from "~/components/ChatWidget";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      {/* suppressHydrationWarning: Grammarly and similar extensions inject
          attributes (data-gr-ext-installed, data-new-gr-c-s-check-loaded)
          onto <body> before React hydrates, which otherwise triggers a
          hydration mismatch warning. */}
      <body suppressHydrationWarning>
        <TRPCReactProvider>
          <SessionProvider>
            <Navbar />
            {children}
            <ChatWidget />
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
