//Alexander Tu
// 02/11/2025

// Dylan Hartley
// 12/12/2025

import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/Navbar";
import SessionProvider from "~/components/SessionProvider";
import ChatWidget from "~/components/ChatWidget";
import { auth } from "~/server/auth";
import { db } from "~/server/db";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  let fontScale = 1.0;

  if (session?.user?.email) {
    const user = await db.user.findUnique({
      where: { email: session.user.email },
      include: { settings: true },
    });

    if (typeof user?.settings?.fontScale === "number") {
      fontScale = user.settings.fontScale;
    }
  }

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <div
          style={
            {
              "--font-scale": fontScale,
              fontSize: "calc(16px * var(--font-scale, 1))",
            } as React.CSSProperties
          }
        >
          <TRPCReactProvider>
            <SessionProvider>
              <Navbar />
              {children}
              <ChatWidget />
            </SessionProvider>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}